export const CREATE_DB = 'CREATED_DB'
export const ADD_DB = 'ADD_DB'
export const CHECK_DB = 'CHECK_DB'
export const REDUCE_DB = 'REDUCE_DB'
export const DELETE_DB = 'DELETE_DB'
export const CLEAR_DB = 'CLEAR_DB'
export const UPDATE_DB = 'UPDATE_DB'
